name: Build Windows App

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build and package .exe
      run: npm run package
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Executable
        path: release/*.exe
